// Dictionnaire d'i18n centralisé. Les clés sont en notation pointée par
// composant/zone (ex. `nav.text`, `settings.theme.dark`). Chaque clé
// existe dans `fr` ET `en` ; un fallback automatique gère les éventuelles
// clés manquantes (cf. `i18n.tsx`).
//
// Variables : `{name}` est remplacé par `vars.name` dans `t(key, vars)`.

export type Lang = "fr" | "en";

export const STRINGS = {
  fr: {
    // Sidebar / navigation
    "nav.text": "Texte",
    "nav.images": "Images",
    "nav.links": "Liens",
    "nav.notes": "Notes",
    "nav.password": "Générateur de mot de passe",
    "nav.settings": "Réglages",
    "nav.system": "Système",
    "nav.capture": "Capture d'écran (Alt+C)",
    "nav.capture.normal": "Capture normale",
    "nav.capture.delayed": "Différée (5s)",
    "nav.capture.ocr": "Capture OCR",

    // TitleBar
    "titlebar.pin": "Toujours au premier plan",
    "titlebar.minimize": "Réduire",
    "titlebar.maximize": "Agrandir",
    "titlebar.close": "Fermer",
    "titlebar.search.placeholder": "Rechercher...",

    // Settings overlay
    "settings.title": "Réglages",
    "settings.themes.dark": "THÈMES SOMBRES",
    "settings.themes.light": "THÈMES CLAIRS",
    "settings.language": "Langue",
    "settings.language.desc": "Langue de l'interface utilisateur.",
    "settings.language.fr": "Français",
    "settings.language.en": "English",
    "settings.capture.label": "Mode automatique",
    "settings.capture.desc": "Surveille votre presse-papier et enregistre automatiquement chaque copie.",
    "settings.autostart.label": "Lancer au démarrage de Windows",
    "settings.autostart.desc": "Lance TyroLabs automatiquement au démarrage de Windows.",
    "settings.autostart.retry": "Réessayer",
    "settings.history.label": "Historique max.",
    "settings.copyright": "© 2026 TyroLabs. Tous droits réservés.",
    "settings.app.version": "TyroLabs V{version}",

    // System drawer
    "sys.title": "Informations système",
    "sys.section.network": "Réseau",
    "sys.section.system": "Système",
    "sys.section.hardware": "Matériel",
    "sys.section.runtimes": "Environnements",
    "sys.section.processes": "Processus",
    "sys.field.hostname": "Nom d'hôte",
    "sys.field.local_ip": "IP locale",
    "sys.field.public_ip": "IP publique",
    "sys.field.mac": "Adresse MAC",
    "sys.field.dns": "Serveurs DNS",
    "sys.field.os": "Système d'exploitation",
    "sys.field.cpu": "Processeur",
    "sys.field.ram": "Mémoire vive",
    "sys.field.disks": "Disques",
    "sys.field.gpu": "Carte graphique",
    "sys.field.gpu.driver": "Pilote",
    "sys.field.java": "Java",
    "sys.field.app_version": "TyroLabs V{version}",
    "sys.processes.refresh": "Rafraîchir",
    "sys.processes.pid": "PID",
    "sys.processes.name": "Nom",
    "sys.processes.cpu": "CPU",
    "sys.processes.ram": "Mémoire",
    "sys.processes.kill": "Tuer",
    "sys.processes.kill.confirm": "Confirmer ?",
    "sys.processes.kill.cancel": "Annuler",
    "sys.processes.kill.success": "Processus terminé ✓",
    "sys.processes.kill.failed": "Échec de la fermeture",
    "sys.copy.success": "Copié ✓",
    "sys.public_ip.loading": "résolution…",
    "sys.public_ip.unavailable": "indisponible",
    "sys.disk.template": "{name} : {free} libre / {total}",

    // Capture overlay
    "capture.ocr.success": "Texte copié ({count} caractères) ✓",
    "capture.ocr.empty": "Aucun texte détecté",
    "capture.ocr.failed": "Erreur OCR : {error}",
    "capture.save.success": "Capture ajoutée ✓",
    "capture.save.failed": "Échec de la capture",
    "capture.prepare.failed": "Erreur lors de la préparation de la capture",

    // Status bar
    "status.label.text": "texte",
    "status.label.images": "image",
    "status.label.links": "lien",
    "status.label.notes": "note",
    "status.label.fallback": "élément",
    "status.selected": "{n} sélectionné{s}",

    // Context menu
    "ctx.copy": "Copier",
    "ctx.copyImage": "Copier l'image",
    "ctx.copyPlain": "Copier texte brut",
    "ctx.pin": "Épingler",
    "ctx.unpin": "Désépingler",
    "ctx.edit": "Éditer",
    "ctx.rename": "Renommer",
    "ctx.delete": "Supprimer",
    "ctx.open": "Ouvrir",
    "ctx.openInPaint": "Ouvrir dans Paint",

    // Editor panel
    "editor.title.text": "Éditer le texte",
    "editor.title.link": "Éditer le lien",
    "editor.title.image": "Renommer l'image",
    "editor.save": "Enregistrer",
    "editor.save.copy": "Enregistrer et copier",
    "editor.cancel": "Annuler",
    "editor.tool.clean": "Nettoyer le formatage (enlève les lignes vides)",
    "editor.tool.upper": "Majuscules",
    "editor.tool.lower": "Minuscules",
    "editor.tool.trim": "Supprimer les espaces multiples",

    // Collections (clipboard)
    "collections.create": "Créer une collection",
    "collections.create.title": "Nouvelle collection",
    "collections.create.confirm": "Créer la collection",
    "collections.create.name": "Nom",
    "collections.create.name.placeholder": "Nom de la collection...",
    "collections.create.icon": "Icône",
    "collections.create.color": "Couleur",
    "collections.create.preview": "Aperçu",
    "collections.create.cancel": "Annuler",
    "collections.rename": "Renommer",
    "collections.delete.confirm.title": "Supprimer la collection ?",
    "collections.delete.confirm.message": "Es-tu sûr de vouloir supprimer cette collection ? Les éléments à l'intérieur ne seront pas supprimés mais ils ne seront plus regroupés.",
    "collections.silo.text": "Texte",
    "collections.silo.image": "Images",
    "collections.silo.link": "Liens",
    "empty.no_results": "Aucun résultat",
    "empty.no_links": "Aucun lien",
    "empty.copy_link_or_path": "Copiez un lien ou un chemin de fichier",
    "empty.thumbnail_unavailable": "Miniature indisponible",

    // Notes
    "notes.create": "Nouvelle note",
    "notes.untitled": "Sans titre",
    "notes.empty.title": "Aucune note",
    "notes.empty.filtered": "Aucune note ne correspond à ces filtres",
    "notes.empty.desc": "Créez votre première note pour commencer.",
    "notes.search.placeholder": "Rechercher une note…",
    "notes.editor.title.placeholder": "Titre de la note",
    "notes.editor.body.placeholder": "Commencez à écrire…",
    "notes.editor.save": "Enregistrer",
    "notes.editor.export": "Exporter en .md",
    "notes.editor.delete": "Supprimer la note",
    "notes.tag.placeholder": "Ajouter un tag",
    "notes.tag.add": "Ajouter",
    "notes.collections.all": "Toutes les notes",
    "notes.collections.untagged": "Sans collection",
    "notes.section.collections": "Collections",
    "notes.section.tags": "Tags",
    "notes.tags.empty": "Aucun tag",
    "notes.tags.clear": "Effacer les tags actifs",
    "notes.collection.new.tooltip": "Nouvelle collection",
    "notes.collection.delete.tooltip": "Supprimer la collection",
    "notes.deleted": "Note supprimée ✓",
    "notes.exported": "Note exportée ✓",
    "notes.export.failed": "Erreur lors de l'export",
    "notes.create.failed": "Erreur lors de la création",
    "notes.rename.failed": "Erreur lors du renommage",
    "notes.collection.deleted": "Collection supprimée ✓",
    "notes.collection.created": "Collection créée ✓",
    "notes.created": "Note créée ✓",
    "notes.moved": "Note déplacée ✓",

    // Password generator
    "password.title": "Générateur de mot de passe",
    "password.mode.random": "Aléatoire",
    "password.mode.passphrase": "Phrase de passe",
    "password.length": "Longueur",
    "password.classes.upper": "Majuscules (A-Z)",
    "password.classes.lower": "Minuscules (a-z)",
    "password.classes.digits": "Chiffres (0-9)",
    "password.classes.symbols": "Symboles (!@#$…)",
    "password.extra": "Caractères additionnels",
    "password.extra.placeholder": "ex. €£¥",
    "password.exclude_ambiguous": "Exclure les ambigus (l, 1, I, O, 0)",
    "password.passphrase.words": "Nombre de mots",
    "password.passphrase.separator": "Séparateur",
    "password.passphrase.capitalize": "Capitaliser",
    "password.passphrase.digits": "Ajouter des chiffres",
    "password.passphrase.symbol": "Ajouter un symbole",
    "password.regenerate": "Régénérer",
    "password.copy": "Copier",
    "password.copied": "Mot de passe copié ✓",
    "password.entropy": "{bits} bits d'entropie",
    "password.strength.0": "Très faible",
    "password.strength.1": "Faible",
    "password.strength.2": "Moyen",
    "password.strength.3": "Fort",
    "password.strength.4": "Très fort",
    "password.error": "Erreur lors de la génération",

    // Toasts génériques
    "toast.copied": "Copié ✓",
    "toast.image_copied": "Image copiée ✓",
    "toast.deleted": "Élément supprimé ✓",
    "toast.deleted.batch": "{n} élément{s} supprimé{s} ✓",
    "toast.copy.failed": "Erreur lors de la copie",
    "toast.delete.failed": "Erreur lors de la suppression",
    "toast.move.failed": "Erreur lors du déplacement",
    "toast.move.batch": "{n} élément{s} déplacé{s} ✓",
    "toast.merge.batch": "{n} élément{s} fusionné{s} ✓",
    "toast.merge.first_image": "1ère image copiée (sélection multiple)",
    "toast.save.failed": "Erreur lors de l'enregistrement",
    "toast.save.success": "Modifications enregistrées ✓",
    "toast.plain.success": "Texte brut copié ✓",
    "toast.settings.failed": "Erreur lors de l'enregistrement des réglages",

    // Misc
    "common.cancel": "Annuler",
    "common.ok": "OK",
    "common.save": "Enregistrer",
    "common.delete": "Supprimer",
    "common.confirm": "Confirmer",
    "common.close": "Fermer",
    "common.copy": "Copier",
    "common.unknown": "inconnu",
  },

  en: {
    // Sidebar / navigation
    "nav.text": "Text",
    "nav.images": "Images",
    "nav.links": "Links",
    "nav.notes": "Notes",
    "nav.password": "Password generator",
    "nav.settings": "Settings",
    "nav.system": "System",
    "nav.capture": "Screen capture (Alt+C)",
    "nav.capture.normal": "Normal capture",
    "nav.capture.delayed": "Delayed (5s)",
    "nav.capture.ocr": "OCR capture",

    // TitleBar
    "titlebar.pin": "Always on top",
    "titlebar.minimize": "Minimize",
    "titlebar.maximize": "Maximize",
    "titlebar.close": "Close",
    "titlebar.search.placeholder": "Search...",

    // Settings overlay
    "settings.title": "Settings",
    "settings.themes.dark": "DARK THEMES",
    "settings.themes.light": "LIGHT THEMES",
    "settings.language": "Language",
    "settings.language.desc": "User interface language.",
    "settings.language.fr": "Français",
    "settings.language.en": "English",
    "settings.capture.label": "Auto capture",
    "settings.capture.desc": "Watches your clipboard and saves every copy automatically.",
    "settings.autostart.label": "Start with Windows",
    "settings.autostart.desc": "Launches TyroLabs automatically on Windows startup.",
    "settings.autostart.retry": "Retry",
    "settings.history.label": "Max history",
    "settings.copyright": "© 2026 TyroLabs. All rights reserved.",
    "settings.app.version": "TyroLabs V{version}",

    // System drawer
    "sys.title": "System information",
    "sys.section.network": "Network",
    "sys.section.system": "System",
    "sys.section.hardware": "Hardware",
    "sys.section.runtimes": "Runtimes",
    "sys.section.processes": "Processes",
    "sys.field.hostname": "Hostname",
    "sys.field.local_ip": "Local IP",
    "sys.field.public_ip": "Public IP",
    "sys.field.mac": "MAC address",
    "sys.field.dns": "DNS servers",
    "sys.field.os": "Operating system",
    "sys.field.cpu": "CPU",
    "sys.field.ram": "RAM",
    "sys.field.disks": "Disks",
    "sys.field.gpu": "GPU",
    "sys.field.gpu.driver": "Driver",
    "sys.field.java": "Java",
    "sys.field.app_version": "TyroLabs V{version}",
    "sys.processes.refresh": "Refresh",
    "sys.processes.pid": "PID",
    "sys.processes.name": "Name",
    "sys.processes.cpu": "CPU",
    "sys.processes.ram": "Memory",
    "sys.processes.kill": "Kill",
    "sys.processes.kill.confirm": "Confirm?",
    "sys.processes.kill.cancel": "Cancel",
    "sys.processes.kill.success": "Process killed ✓",
    "sys.processes.kill.failed": "Failed to kill process",
    "sys.copy.success": "Copied ✓",
    "sys.public_ip.loading": "resolving…",
    "sys.public_ip.unavailable": "unavailable",
    "sys.disk.template": "{name}: {free} free / {total}",

    // Capture overlay
    "capture.ocr.success": "Text copied ({count} chars) ✓",
    "capture.ocr.empty": "No text detected",
    "capture.ocr.failed": "OCR error: {error}",
    "capture.save.success": "Capture added ✓",
    "capture.save.failed": "Capture failed",
    "capture.prepare.failed": "Failed to prepare capture",

    // Status bar
    "status.label.text": "text item",
    "status.label.images": "image",
    "status.label.links": "link",
    "status.label.notes": "note",
    "status.label.fallback": "item",
    "status.selected": "{n} selected",

    // Context menu
    "ctx.copy": "Copy",
    "ctx.copyImage": "Copy image",
    "ctx.copyPlain": "Copy plain text",
    "ctx.pin": "Pin",
    "ctx.unpin": "Unpin",
    "ctx.edit": "Edit",
    "ctx.rename": "Rename",
    "ctx.delete": "Delete",
    "ctx.open": "Open",
    "ctx.openInPaint": "Open in Paint",

    // Editor panel
    "editor.title.text": "Edit text",
    "editor.title.link": "Edit link",
    "editor.title.image": "Rename image",
    "editor.save": "Save",
    "editor.save.copy": "Save and copy",
    "editor.cancel": "Cancel",
    "editor.tool.clean": "Clean formatting (drop empty lines)",
    "editor.tool.upper": "Uppercase",
    "editor.tool.lower": "Lowercase",
    "editor.tool.trim": "Collapse extra whitespace",

    // Collections (clipboard)
    "collections.create": "Create a collection",
    "collections.create.title": "New collection",
    "collections.create.confirm": "Create collection",
    "collections.create.name": "Name",
    "collections.create.name.placeholder": "Collection name...",
    "collections.create.icon": "Icon",
    "collections.create.color": "Color",
    "collections.create.preview": "Preview",
    "collections.create.cancel": "Cancel",
    "collections.rename": "Rename",
    "collections.delete.confirm.title": "Delete this collection?",
    "collections.delete.confirm.message": "Are you sure you want to delete this collection? Items inside will not be deleted but will no longer be grouped.",
    "collections.silo.text": "Text",
    "collections.silo.image": "Images",
    "collections.silo.link": "Links",
    "empty.no_results": "No results",
    "empty.no_links": "No links",
    "empty.copy_link_or_path": "Copy a URL or a file path",
    "empty.thumbnail_unavailable": "Thumbnail unavailable",

    // Notes
    "notes.create": "New note",
    "notes.untitled": "Untitled",
    "notes.empty.title": "No notes",
    "notes.empty.filtered": "No notes match these filters",
    "notes.empty.desc": "Create your first note to get started.",
    "notes.search.placeholder": "Search notes…",
    "notes.editor.title.placeholder": "Note title",
    "notes.editor.body.placeholder": "Start writing…",
    "notes.editor.save": "Save",
    "notes.editor.export": "Export as .md",
    "notes.editor.delete": "Delete note",
    "notes.tag.placeholder": "Add tag",
    "notes.tag.add": "Add",
    "notes.collections.all": "All notes",
    "notes.collections.untagged": "No collection",
    "notes.section.collections": "Collections",
    "notes.section.tags": "Tags",
    "notes.tags.empty": "No tags",
    "notes.tags.clear": "Clear active tags",
    "notes.collection.new.tooltip": "New collection",
    "notes.collection.delete.tooltip": "Delete collection",
    "notes.deleted": "Note deleted ✓",
    "notes.exported": "Note exported ✓",
    "notes.export.failed": "Export failed",
    "notes.create.failed": "Failed to create",
    "notes.rename.failed": "Failed to rename",
    "notes.collection.deleted": "Collection deleted ✓",
    "notes.collection.created": "Collection created ✓",
    "notes.created": "Note created ✓",
    "notes.moved": "Note moved ✓",

    // Password generator
    "password.title": "Password generator",
    "password.mode.random": "Random",
    "password.mode.passphrase": "Passphrase",
    "password.length": "Length",
    "password.classes.upper": "Uppercase (A-Z)",
    "password.classes.lower": "Lowercase (a-z)",
    "password.classes.digits": "Digits (0-9)",
    "password.classes.symbols": "Symbols (!@#$…)",
    "password.extra": "Extra characters",
    "password.extra.placeholder": "e.g. €£¥",
    "password.exclude_ambiguous": "Exclude ambiguous (l, 1, I, O, 0)",
    "password.passphrase.words": "Word count",
    "password.passphrase.separator": "Separator",
    "password.passphrase.capitalize": "Capitalize",
    "password.passphrase.digits": "Append digits",
    "password.passphrase.symbol": "Append a symbol",
    "password.regenerate": "Regenerate",
    "password.copy": "Copy",
    "password.copied": "Password copied ✓",
    "password.entropy": "{bits} bits of entropy",
    "password.strength.0": "Very weak",
    "password.strength.1": "Weak",
    "password.strength.2": "Fair",
    "password.strength.3": "Strong",
    "password.strength.4": "Very strong",
    "password.error": "Generation failed",

    // Generic toasts
    "toast.copied": "Copied ✓",
    "toast.image_copied": "Image copied ✓",
    "toast.deleted": "Item deleted ✓",
    "toast.deleted.batch": "{n} item{s} deleted ✓",
    "toast.copy.failed": "Copy failed",
    "toast.delete.failed": "Delete failed",
    "toast.move.failed": "Move failed",
    "toast.move.batch": "{n} item{s} moved ✓",
    "toast.merge.batch": "{n} item{s} merged ✓",
    "toast.merge.first_image": "1st image copied (multi-select)",
    "toast.save.failed": "Save failed",
    "toast.save.success": "Changes saved ✓",
    "toast.plain.success": "Plain text copied ✓",
    "toast.settings.failed": "Failed to save settings",

    // Misc
    "common.cancel": "Cancel",
    "common.ok": "OK",
    "common.save": "Save",
    "common.delete": "Delete",
    "common.confirm": "Confirm",
    "common.close": "Close",
    "common.copy": "Copy",
    "common.unknown": "unknown",
  },
} as const;

export type StringKey = keyof (typeof STRINGS)["fr"];
