import type { Theme, ThemeId } from "./types";

export const THEMES: Record<ThemeId, Theme> = {
  // ──── Dark themes ────────────────────────────────────────
  command: {
    id: "command",
    name: "Command",
    desc: "Sobre & chirurgical",
    accent: "#3B82F6",
    accentRGB: "59,130,246",
    fontUI: "'Space Grotesk', sans-serif",
    fontMono: "'JetBrains Mono', monospace",
    iconStroke: 1.5,
    logoPrefix: "[ ",
    logoSuffix: " ]",
    logoLetterSpacing: "0.07em",
    bg: "#09090B",
    sidebar: "#0E0E10",
  },
  neon: {
    id: "neon",
    name: "Neon",
    desc: "Cyberpunk & contrasté",
    accent: "#00FF88",
    accentRGB: "0,255,136",
    fontUI: "'JetBrains Mono', monospace",
    fontMono: "'JetBrains Mono', monospace",
    iconStroke: 1,
    logoPrefix: "> ",
    logoSuffix: " <",
    logoLetterSpacing: "0.14em",
    bg: "#020208",
    sidebar: "#06060F",
  },
  obsidian: {
    id: "obsidian",
    name: "Obsidian",
    desc: "Chaud & ambré",
    accent: "#F59E0B",
    accentRGB: "245,158,11",
    fontUI: "'Outfit', sans-serif",
    fontMono: "'IBM Plex Mono', monospace",
    iconStroke: 2,
    logoPrefix: "/ ",
    logoSuffix: " /",
    logoLetterSpacing: "0.09em",
    bg: "#0C0A07",
    sidebar: "#110E09",
  },
  arctic: {
    id: "arctic",
    name: "Arctic",
    desc: "Froid & polaire",
    accent: "#22D3EE",
    accentRGB: "34,211,238",
    fontUI: "'Syne', sans-serif",
    fontMono: "'IBM Plex Mono', monospace",
    iconStroke: 1.5,
    logoPrefix: "◦ ",
    logoSuffix: " ◦",
    logoLetterSpacing: "0.15em",
    bg: "#07090D",
    sidebar: "#0A0C13",
  },
  carbon: {
    id: "carbon",
    name: "Carbon",
    desc: "Industriel & intense",
    accent: "#EF4444",
    accentRGB: "239,68,68",
    fontUI: "'Space Grotesk', sans-serif",
    fontMono: "'JetBrains Mono', monospace",
    iconStroke: 2.5,
    logoPrefix: "| ",
    logoSuffix: " |",
    logoLetterSpacing: "0.10em",
    bg: "#0A0808",
    sidebar: "#100B0B",
  },

  // ──── Light themes ───────────────────────────────────────
  daylight: {
    id: "daylight",
    name: "Daylight",
    desc: "Lumineux & net",
    accent: "#2563EB",
    accentRGB: "37,99,235",
    fontUI: "'Space Grotesk', sans-serif",
    fontMono: "'JetBrains Mono', monospace",
    iconStroke: 1.5,
    logoPrefix: "[ ",
    logoSuffix: " ]",
    logoLetterSpacing: "0.07em",
    bg: "#E2E8F0",
    sidebar: "#CBD5E1",
    light: true,
    t1: "#0F172A",
    t2: "#475569",
    t3: "#64748B",
    border: "#94A3B8",
    borderDim: "rgba(148,163,184,0.7)",
    rowHov: "#CBD5E1",
  },
  cream: {
    id: "cream",
    name: "Cream",
    desc: "Doux & chaleureux",
    accent: "#D97706",
    accentRGB: "217,119,6",
    fontUI: "'Outfit', sans-serif",
    fontMono: "'IBM Plex Mono', monospace",
    iconStroke: 1.8,
    logoPrefix: "~ ",
    logoSuffix: " ~",
    logoLetterSpacing: "0.08em",
    bg: "#EBE3D5",
    sidebar: "#DED3C1",
    light: true,
    t1: "#292524",
    t2: "#57534E",
    t3: "#78716C",
    border: "#C8B9A6",
    borderDim: "rgba(200,185,166,0.7)",
    rowHov: "#DED3C1",
  },
  sakura: {
    id: "sakura",
    name: "Sakura",
    desc: "Fleuri & délicat",
    accent: "#DB2777",
    accentRGB: "219,39,119",
    fontUI: "'Syne', sans-serif",
    fontMono: "'IBM Plex Mono', monospace",
    iconStroke: 1.5,
    logoPrefix: "❀ ",
    logoSuffix: " ❀",
    logoLetterSpacing: "0.10em",
    bg: "#F3E1E8",
    sidebar: "#E6D1D9",
    light: true,
    t1: "#2B1921",
    t2: "#604851",
    t3: "#826671",
    border: "#D1B6C1",
    borderDim: "rgba(209,182,193,0.7)",
    rowHov: "#E6D1D9",
  },
  mint: {
    id: "mint",
    name: "Mint",
    desc: "Frais & apaisant",
    accent: "#059669",
    accentRGB: "5,150,105",
    fontUI: "'Space Grotesk', sans-serif",
    fontMono: "'JetBrains Mono', monospace",
    iconStroke: 1.5,
    logoPrefix: "• ",
    logoSuffix: " •",
    logoLetterSpacing: "0.09em",
    bg: "#E1EBE6",
    sidebar: "#D2E0DA",
    light: true,
    t1: "#06402B",
    t2: "#3D6E5A",
    t3: "#66927E",
    border: "#BACFC5",
    borderDim: "rgba(186,207,197,0.7)",
    rowHov: "#D2E0DA",
  },
  cloud: {
    id: "cloud",
    name: "Cloud",
    desc: "Aérien & minimal",
    accent: "#6366F1",
    accentRGB: "99,102,241",
    fontUI: "'Space Grotesk', sans-serif",
    fontMono: "'JetBrains Mono', monospace",
    iconStroke: 1.5,
    logoPrefix: "○ ",
    logoSuffix: " ○",
    logoLetterSpacing: "0.12em",
    bg: "#E2E6F0",
    sidebar: "#D4D9E6",
    light: true,
    t1: "#171B38",
    t2: "#4F567A",
    t3: "#7780A6",
    border: "#BEC6D9",
    borderDim: "rgba(190,198,217,0.7)",
    rowHov: "#D4D9E6",
  },
};
