import type { Theme, ThemeId } from "./types";

export const THEMES: Record<ThemeId, Theme> = {
  command: {
    id: "command",
    name: "Command",
    desc: "Sobre & chirurgical",
    accent: "#3B82F6",
    accentRGB: "59,130,246",
    fontUI: "'Space Grotesk', sans-serif",
    fontMono: "'JetBrains Mono', monospace",
    iconStroke: 1.5,
    logoPrefix: "[ ",
    logoSuffix: " ]",
    logoLetterSpacing: "0.07em",
    bg: "#09090B",
    sidebar: "#0E0E10",
  },
  neon: {
    id: "neon",
    name: "Neon",
    desc: "Cyberpunk & contrasté",
    accent: "#00FF88",
    accentRGB: "0,255,136",
    fontUI: "'JetBrains Mono', monospace",
    fontMono: "'JetBrains Mono', monospace",
    iconStroke: 1,
    logoPrefix: "> ",
    logoSuffix: " <",
    logoLetterSpacing: "0.14em",
    bg: "#020208",
    sidebar: "#06060F",
  },
  obsidian: {
    id: "obsidian",
    name: "Obsidian",
    desc: "Chaud & ambré",
    accent: "#F59E0B",
    accentRGB: "245,158,11",
    fontUI: "'Outfit', sans-serif",
    fontMono: "'IBM Plex Mono', monospace",
    iconStroke: 2,
    logoPrefix: "/ ",
    logoSuffix: " /",
    logoLetterSpacing: "0.09em",
    bg: "#0C0A07",
    sidebar: "#110E09",
  },
  arctic: {
    id: "arctic",
    name: "Arctic",
    desc: "Froid & polaire",
    accent: "#22D3EE",
    accentRGB: "34,211,238",
    fontUI: "'Syne', sans-serif",
    fontMono: "'IBM Plex Mono', monospace",
    iconStroke: 1.5,
    logoPrefix: "◦ ",
    logoSuffix: " ◦",
    logoLetterSpacing: "0.15em",
    bg: "#07090D",
    sidebar: "#0A0C13",
  },
  carbon: {
    id: "carbon",
    name: "Carbon",
    desc: "Industriel & intense",
    accent: "#EF4444",
    accentRGB: "239,68,68",
    fontUI: "'Space Grotesk', sans-serif",
    fontMono: "'JetBrains Mono', monospace",
    iconStroke: 2.5,
    logoPrefix: "| ",
    logoSuffix: " |",
    logoLetterSpacing: "0.10em",
    bg: "#0A0808",
    sidebar: "#100B0B",
  },
};
